---
title: "ngDNA_volfilt_PinkSal_Finnmark"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown



```{r, echo=FALSE}
library(here)
library(readr)
library(magrittr)
library(dplyr)
library(ggplot2)
library(cowplot)
library(ggpubr)
library(gridExtra)
library(tidyr)
library(leaflet)
library(mapview)
Sys.setlocale(locale='no_NB.utf8')
Sys.getlocale()
remotes::install_github("r-spatial/mapview")

```

## Read quantification data from the two plates from GJE, rbind to one table

```{r}
ps_finn_q1 <- read_delim(here("data", "EEG_2021-11-02-plt1_pukkellaks_finnmark_CFX96.txt")) 
ps_finn_q2 <- read_delim(here("data", "EEG_2021-11-03-plt2_pukkellaks_finnmark_CFX96.txt"))
ps_finn <- rbind(ps_finn_q1, ps_finn_q2)

quant_pinksal_finn <- ps_finn %>% mutate(detect = ifelse(SQ == "NaN", 0, 1))

samples <- readxl::read_xlsx(here("data", "eDNAsamples_2021.xlsx")) %>%
  janitor::clean_names(.) %>% 
  mutate(across(extraction_date, ~ as.Date(as.character(.), format = '%Y-%m-%d'))) %>%
  mutate(provetatt2 = as.character(provetatt)) %>%
  mutate(across(provetatt, ~ as.Date(as.character(.), format = '%d.%m.%Y'))) %>%
  mutate(across(volum, ~as.numeric(.))) %>% 
  mutate(qbit1 = as.numeric(dna_ng_m_l_qubit_read1)) %>% 
  mutate(qbit2 = as.numeric(dna_ng_m_l_qubit_read2)) %>% 
  mutate(qbit_avg = (qbit1+qbit2)/2) %>% 
  mutate(ngDNA_filt_volenhet = ((150*qbit_avg)/volum)) %>% 
  mutate(tot_ngDNA = 150*qbit_avg) %>% mutate(dybde = as.numeric(dybde)) %>% 
  rename(dyp = dybde)

```
## Modify qPCR data file
Add dummy variable indicating qPCR technical replicate
Transform SQ to numeric
Arrange according to descending sample number for plotting
Add sampling station variable
Create new variable ng DNA / volume of filtered water

```{r}
ps_finn_forplot <- quant_pinksal_finn %>% dplyr::select(Content, Sample, Cq, SQ, detect) %>% dplyr::filter(Sample %in% as.character(c(567:584))) %>% 
  dplyr::arrange(desc(Sample)) %>% dplyr::mutate(Sample = factor(Sample)) %>% dplyr::mutate(SQ = as.numeric(SQ)) %>% 
  dplyr::mutate(tech_rep = factor(rep(c(1:6), 18))) %>%  
 left_join(., samples, by = c("Sample" = "provenr")) %>% mutate(SQ_vol = SQ/volum) %>% 
  mutate(stasjon = factor(as.character(stasjon, ordered = T, levels = c("4","3","2","1","5","6"))))

nrep_pinksal_fin <- ps_finn_forplot %>% dplyr::group_by(Sample, sample_rep, stasjon) %>% count()
ndetect_pinksal_fin <- ps_finn_forplot %>% dplyr::group_by(Sample, sample_rep, stasjon) %>% summarise(num_detect = sum(detect))

pinksal_nrepdet <- left_join(nrep_pinksal_fin, ndetect_pinksal_fin, by = "Sample") %>% dplyr::select(-sample_rep.y, -stasjon.y) %>% rename(stasjon = stasjon.x, sample_rep = sample_rep.x) %>% 
  mutate(stasjon = factor(as.character(stasjon, ordered = T, levels = c("4","3","2","1","5","6"))))



stasj_dist <- read_delim(here("data", "stasj_lat_lon4.txt"), delim = "\t") %>% dplyr::filter(fylke %in% c("Finnmark")) %>% 
  mutate(stasjon = factor(as.character(stasjon, ordered = T, levels = c("4","3","2","1","5","6"))))


pinksal_nrepdet_forplot <- left_join(pinksal_nrepdet, stasj_dist, by = "stasjon") %>% mutate(fraction = stringr::str_c(num_detect, n, sep = "/")) %>% ungroup() %>% dplyr::select(sample_rep, stasjon, fraction)

pinksal_nrepdet_forplot_wide <- pinksal_nrepdet_forplot %>% pivot_wider(names_from = stasjon, values_from = fraction) %>% dplyr::select(`4`, `3`, `2`, `1`, `5`, `6`)


eDNAconc_pinksal_finn <- left_join(ps_finn_forplot, stasj_dist, by = c("innsjo" = "innsjo", "stasjon" = "stasjon", "dyp" = "dyp")) %>% dplyr::select(Sample, Cq, SQ, sample_rep, tech_rep, dyp, stasjon, innsjo, fylke.y, volum, SQ_vol, lat, lon, provetatt, dist_hav) %>% rename(fylke = "fylke.y")

write_delim(eDNAconc_pinksal_finn, "eDNAconc_pinksal_finn.txt", delim = "\t")

#### calculate median concentration ####
medeDNAconc_pinksal <- eDNAconc_pinksal_finn %>%  group_by(lat, lon, stasjon, fylke) %>% summarise_if(is.numeric, ~median(., na.rm = T))

medeDNAconc_pinksal[is.na(medeDNAconc_pinksal)] <- 0


#### Langs grense jakobselv, kart ####
medeDNAconc_pinksal_finn <- medeDNAconc_pinksal %>% dplyr::filter(fylke == "Finnmark")


medeDNAconc_pinksal_finn_map <- leaflet(medeDNAconc_pinksal_finn) %>% 
    addTiles() %>% 
     fitBounds(~min(lon, na.rm = TRUE), ~min(lat, na.rm = TRUE), ~max(lon, na.rm = TRUE), ~max(lat, na.rm = TRUE)+0.04) %>% 
  addCircleMarkers(color = "red", radius = ~log(SQ_vol*1e11, base = 10)) #%>% 
  # addLabelOnlyMarkers(label = ~as.character(stasjon), labelOptions = labelOptions(noHide = T, direction = 'left', textOnly = T, textsize = "20px"))

mapshot(medeDNAconc_pinksal_finn_map, file = "eDNAconc_pinksal_finn_map2.png")



stasj_dist <- read_delim(here("data", "stasj_havdist_GJE.txt"), delim = "\t") %>% mutate(stasjon = factor(as.character(stasjon, ordered = T, levels = c("4","3","2","1","5","6", "TV", "BT", "LS"))))
  
ps_finn_forplot2 <- left_join(ps_finn_forplot, stasj_dist, by = "stasjon")
#View(quant_samples)
```



```{r}
#### as points ####
ps_finn_plt <- ggplot(data = ps_finn_forplot, aes(x = factor(stasjon, ordered = T, levels =   c("4","3","2","1","5","6", "TV", "BT", "LS")), y = SQ_vol, color = sample_rep))+
  geom_jitter(width = 0.1, size = 1.5)+
  xlab("Stasjon")+
  ylab("Pukkellaks eDNA (ng/mL)")+
  labs(color = "Prøvetakings-\nreplikat")+
  scale_color_manual(values = c("red", "blue", "cyan"))+
  facet_grid(cols = vars(fylke), space = "free_x", scales = "free_x", labeller = as_labeller(c("Finnmark" = "Finnmark - Grense Jakobselv", "Svalbard" = "Svalbard")))+
  scale_y_continuous(trans = "log10")+
  theme_bw()+
  theme(axis.title = element_text(size = 10),
        legend.title = element_text(size = 10))
ps_finn_plt

#### distance from ocean, Grense Jakobselv ####
ps_finn_plt2 <- ggplot(data = ps_finn_forplot2, aes(x = dist_hav, y = SQ_vol, color = sample_rep))+
  geom_jitter(width = 0.1, size = 1.5)+
  xlab("Distanse fra havet (km)")+
  ylab("Pukkellaks eDNA (ng/mL)")+
  labs(color = "Prøvetakings-\nreplikat", title = "Grense Jakobselv")+
  scale_color_manual(values = c("red", "blue", "cyan"))+
  scale_y_continuous(trans = "log10", limits = c(1e-9,5e-3), breaks = c(1e-3, 1e-4, 1e-5, 1e-6, 1e-7, 1e-8, 1e-9))+
  theme_bw()+
  theme(axis.title = element_text(size = 10),
        legend.title = element_text(size = 10),
        plot.title = element_text(hjust = 0.5, size = 12))
ps_finn_plt2

ps_sval_plt <- ggplot(data = ps_finn_forplot %>% dplyr::filter(fylke == "Svalbard"), aes(x = stasjon, y = SQ_vol, color = sample_rep))+
  geom_jitter(width = 0.1, size = 1.5)+
  xlab("Stasjon")+
  ylab("Pukkellaks eDNA (ng/mL)")+
  labs(color = "Prøvetakings-\nreplikat")+
  scale_color_manual(values = c("red", "blue", "cyan"))+
  scale_y_continuous(trans = "log10", limits = c(1e-9,5e-3), breaks = c(1e-3, 1e-4, 1e-5, 1e-6, 1e-7, 1e-8, 1e-9), labels = NULL)+
  theme_bw()+
  labs(title = "Svalbard")+
  theme(axis.title = element_text(size = 10),
        legend.title = element_text(size = 10),
        axis.title.y = element_blank(),
        plot.title = element_text(hjust = 0.5, size = 12))
ps_sval_plt


png(filename = "pinksal_finmark_svalbard_hires.png", width = 2300, height = 1000,
    units = "px", pointsize = 8, bg = "white", res = 300,
    restoreConsole = TRUE)
ggarrange(ps_finn_plt2, ps_sval_plt, common.legend = TRUE, widths = c(2,1))
dev.off()


```

